import Head from "next/head"
import Image from "next/image"
// * Convertir NextJS en SPA
// import Link from "next/link";

import { useEffect, useState } from "react"

import styles from "styles/Home.module.css"

import { loginWithGitHub, onAuthStateChangedF } from "../firebase/client"

import Avatar from "components/Avatar"
import Button from "@c/Button"
import GitHub from "components/Icons/GitHub"
import Logo from "components/Icons/Logo"

// * Ya se vera más adelante
// ! import { useRouter } from 'next/router'

export default function Home() {
  const [user, setUser] = useState(undefined)

  useEffect(() => {
    onAuthStateChangedF(setUser)
  }, [])

  const handleClick = () => {
    loginWithGitHub()
      .then(setUser)
      .catch((err) => {
        console.log(err)
      })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>devter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.containerCenter}>
        <main className={styles.main}>
          <section>
            <Logo width={100} />
            <h1>Devter</h1>
            <h2>Talk about development with developers</h2>
            <div>
              {user === null && (
                <Button onClick={handleClick}>
                  <GitHub fill="#fff" width={24} height={24} />
                  Login with github
                </Button>
              )}
              {user && user.avatar && (
                <div>
                  <Avatar
                    src={user.avatar}
                    alt={user.username}
                    text={user.username}
                    withText
                  />
                </div>
              )}
            </div>
          </section>
        </main>
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
