import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// * Convertir NextJS en SPA
import Link from 'next/link'
import Button from '../components/Button'
import GitHub from '../components/Button/Icons/GitHub'

import {loginWithGitHub} from '../firebase/client'
import { useState } from 'react'

// * Ya se vera más adelante
// ! import { useRouter } from 'next/router'

export default function Home() {

  const [user, setUser] = useState(null)

  const handleClick = () => {
    loginWithGitHub().then(user => {
      setUser(user)
    }).catch(err => {
      console.log(err);
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>devter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.containerCenter}>
        <main className={styles.main}>
          <section>
            <img src="/BrandTransparentMD.png" alt="Logo" />
            <h1>Devter</h1>
            <h2>Talk about development with developers</h2>
            <div>
              <Button onClick={handleClick}>
                <GitHub fill='#fff' width={24} height={24}/>
                Login with github
              </Button>
            </div>
          </section>
        </main>
      </div>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
